ADMIN = "ADMIN"
DONOR = "DONOR"
PATIENT = "PATIENT"


PROFILE_TYPES = (
    (ADMIN, "ADMIN"),
    (DONOR, "DONOR"),
    (PATIENT, "PATIENT"),
)


MALE = "MALE"
FEMALE = "FEMALE"


GENDER_TYPES = (
    (MALE, "MALE"),
    (FEMALE, "FEMALE"),
)


A_POSITIVE = "A+"
A_NEGATIVE = "A-"
B_POSITIVE = "B+"
B_NEGATIVE = "B-"
AB_POSITIVE = "AB+"
AB_NEGATIVE = "AB-"
O_POSITIVE = "O+"
O_NEGATIVE = "O-"


BLOOD_GROUP_TYPES = (
    (A_POSITIVE, "A+"),
    (A_NEGATIVE, "A-"),
    (B_POSITIVE, "B+"),
    (B_NEGATIVE, "B-"),
    (AB_POSITIVE, "AB+"),
    (AB_NEGATIVE, "AB-"),
    (O_POSITIVE, "O+"),
    (O_NEGATIVE, "O-"),
)

PENDING = "PENDING"
SAMPLE_TAKEN = "SAMPLE TAKEN"
SAMPLE_TEST_ONGOING = "SAMPLE TEST ONGOING"
SAMPLE_MATCH = "SAMPLE MATCH"
DELIVERY_ON_PROCESS = "DELIVERY ON PROCESS"
DELIVERY_COMPLETED = "DELIVERY COMPLETED"


REQUEST_STATUS = (
    (PENDING, "PENDING"),
    (SAMPLE_TAKEN, "SAMPLE TAKEN"),
    (SAMPLE_TEST_ONGOING, "SAMPLE TEST ONGOING"),
    (SAMPLE_MATCH, "SAMPLE MATCH"),
    (DELIVERY_ON_PROCESS, "DELIVERY ON PROCESS"),
    (DELIVERY_COMPLETED, "DELIVERY COMPLETED"),
)